//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webservice.api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_0010
    {
        public long MST_CODE { get; set; }
        public decimal MST_MOBI { get; set; }
        public string MST_NAME { get; set; }
        public string MST_MAIL { get; set; }
        public Nullable<bool> FLD_BLCK { get; set; }
        public string FLD_SCDE { get; set; }
        public Nullable<bool> FLD_SECR { get; set; }
        public string MST_DVID { get; set; }
    }
}
